pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      assign:
        users: [toniogela]
      label:
        add: [dependency-update]
  - name: merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - status-success=Build (macOS-latest)
      - status-success=Build (ubuntu-latest)
      - status-success=Build (windows-latest)
    actions:
      merge:
        method: squash
        strict: true
