pull_request_rules:
  - name: assign and label scala-steward's PRs
    conditions:
      - author=scala-steward
    actions:
      assign:
        users: [toniogela]
      label:
        add: [dependency-update]
  - name: merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - status-success=unix (macOS-latest) 
      - status-success=unix (ubuntu-latest)
      - status-success=unix (windows-latest)
    actions:
      merge:
        method: squash
        strict: true
