addSbtPlugin("io.github.davidgregory084" %% "sbt-tpolecat"     % "0.2.3")
addSbtPlugin("org.scalameta"             %% "sbt-scalafmt"     % "2.4.6")
addSbtPlugin("ch.epfl.scala"             %% "sbt-scalafix"     % "0.9.34")
addSbtPlugin("org.scalameta"              % "sbt-native-image" % "0.3.2")
addSbtPlugin("de.heikoseeberger"          % "sbt-header"       % "5.6.5")
