addSbtPlugin("io.github.davidgregory084" %% "sbt-tpolecat"     % "0.1.19")
addSbtPlugin("org.scalameta"             %% "sbt-scalafmt"     % "2.4.2")
addSbtPlugin("ch.epfl.scala"             %% "sbt-scalafix"     % "0.9.29")
addSbtPlugin("org.scalameta"              % "sbt-native-image" % "0.3.0")
addSbtPlugin("de.heikoseeberger"          % "sbt-header"       % "5.6.0")
